#!/usr/bin/env python3

import subprocess
import threading
import time
import os
import json

lock = threading.Lock()

def checkServer(ip):
    output = subprocess.check_output(["ssh", "root@" + ip, "/bin/bash", "/root/tr"])
    lock.acquire()
    print('-'*10, ip, '-' * 10)
    print(output.decode('ascii'))
    lock.release()

if __name__ == '__main__':  
    config = json.loads(open("config.json", "r").read())
    for host in config["servers"]["free"]:
        t = threading.Thread(target=checkServer, args=(host,))
        t.start()