#!/bin/bash

ssh root@do2 "ls -l /var/log/nginx"

echo "count of out.txt in access.log..."
ssh root@do2 "grep out.txt /var/log/nginx/access.log | wc"
ssh root@do2 "grep out.txt /var/log/nginx/access.log.1 | wc"

echo "Removing .gz"
ssh root@do2 "rm /var/log/nginx/*.gz"