#!/bin/bash

printf "github Chromium..."
curl -I https://github.com/jjqqkk/chromium | head -n5
sleep 2

printf "\n######################\n"
printf "config server\n"
printf "######################\n"

curl -I https://raw.githubusercontent.com/forex118899/helloworld/master/out.txt | head 

CONFIG="do2"

printf "\n# listing logs...\n"
ssh root@$CONFIG "ls -l /var/log/nginx"

printf "\n# count of out.txt in access.log...\n"
ssh root@$CONFIG "grep out.txt /var/log/nginx/access.log | wc"
ssh root@$CONFIG "grep out.txt /var/log/nginx/access.log.1 | wc"

printf "\n# Removing .gz\n"
ssh root@$CONFIG "rm /var/log/nginx/*.gz"

printf "\n# vnstat...\n"
ssh root@$CONFIG vnstat