#!/bin/bash

curl -I https://github.com/jjqqkk/chromium | head -n5
sleep 2

printf "\n# listing logs...\n"
ssh root@do2 "ls -l /var/log/nginx"

printf "\n# count of out.txt in access.log...\n"
ssh root@do2 "grep out.txt /var/log/nginx/access.log | wc"
ssh root@do2 "grep out.txt /var/log/nginx/access.log.1 | wc"

printf "\n# Removing .gz\n"
ssh root@do2 "rm /var/log/nginx/*.gz"

printf "\n# vnstat...\n"
ssh root@do2 vnstat