#!/usr/bin/env python3

import subprocess
import threading
import time
import os
import json

lock = threading.Lock()

def checkServer(ip):
    ret = subprocess.call(["ssh", "root@" + ip, "touch", "/tmp/abc"])
    lock.acquire()
    print("%-17s%3d" % (ip, ret))
    lock.release()

if __name__ == '__main__':  
    config = json.loads(open("config.json", "r").read())
    for host in config["servers"]["free"]:
        t = threading.Thread(target=checkServer, args=(host,))
        t.start()