#!/usr/bin/env python3

import subprocess
import threading
import time
import os
import json
import socket
from pathlib import Path

def openBrowser(chromium, ip):
    cmd = "%s --incognito " \
        "--proxy-server=https://cppcoding.site:8443 " \
        "--host-resolver-rules='MAP cppcoding.site %s' https://www.freevpn.pw" % (chromium, 
        ip)
    print(ip)
    os.system(cmd)
    time.sleep(3)

def main():
    config = json.loads(open("config.json", "r").read())
    
    chromium = Path.home().joinpath(".jjqqkk", "chromium")
    loc = open(chromium, "r").read()
    chromiumExec = Path.home().joinpath(".jjqqkk", loc, "Contents", "MacOS", "Chromium")

    for host in config["servers"]["free"]:
        openBrowser(chromiumExec, host)

if __name__ == "__main__":
    main()