#!/bin/bash

../helper config-write config.json > out.txt
node read-config.js |  base64 | base64 | base64 > out2.txt

scp out*.txt root@do2:/var/www/html
#scp out2.txt root@do2:/var/www/html
scp out*.txt root@161.35.168.208:/var/www/html/

git commit -am "Update config"
git push aaa master

# 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

