#!/bin/bash

../helper config-write config.json > out.txt
node read-config.js |  base64 | base64 | base64 > out2.txt

scp out*.txt root@do2:/var/www/html
#scp out2.txt root@do2:/var/www/html

git add out.txt
git add out2.txt
git commit -m "Update config"
git push